HashSlingingStasher (HSS) Submission
hak5/bashbunny-payloads pull request #667
Opened 2023-09-29 02:22 UTC by theSW4n

Version 1.0 submission of the HashSlingingStasher. This is an exfiltration payload for MacOS, Ubuntu and Kali Linux.

2024-09-01 22:07 UTC, hak5peaks requested changes

2025-02-01 16:55 UTC, theSW4n commented on payloads/library/exfiltration/HashSlingingStasher/payload.txt
> +hss_target_directory=/
I incorporated your suggestion however exporting variables directly from payload.txt didn't allow the variables to be accessed by hss_bbscript.sh when executed through the target terminal. Interestingly whenever the payload quacks code into the target terminal with ducky script, the variables set in payload.txt are accessible, so you'll see where I exported the variables using quack strings instead.

2025-02-01 16:57 UTC, theSW4n commented on payloads/library/exfiltration/HashSlingingStasher/payload.txt
> +QUACK STRING "udisksctl mount -b /dev/disk/by-label/`ls /dev/disk/by-label/ | grep -i BashBunny`"
Change incorporated as described in the following change comment.

2025-02-01 16:58 UTC, theSW4n commented on payloads/library/exfiltration/HashSlingingStasher/hss_bbscript.sh
> +target_directory=$(grep -hi hss_target_directory $mountpt/HSS/payload.txt | cut -c 22-)
Change incorporated as described in the other change comments.

2025-02-01 16:59 UTC, theSW4n commented
Requested changes have been incorporated. Please review and approve for merging as needed.

2025-02-02 15:48 UTC, hak5peaks commented
Thank you for making the requested changed. I will review this PR later today 😄

2025-02-04 16:02 UTC, hak5peaks commented on payloads/library/exfiltration/HashSlingingStasher/payload.txt
> +hss_target_directory=/
Sounds good, after further testing I had the same result.

2025-02-04 16:02 UTC, merged